{
"Feedstock_Supply_Logistics": {
        "feedstock.kg": {"high": 8.02, "avg": 7.02, "low": 6.02, "units": "kg per kg ethanol"},
        "electricity": {"high": 0.0009, "avg": 0.0002, "low": 0.0001, "units": "kg per kg ethanol"}},
    "Feedstock_Handling_and_Preparation": {
        "electricity": {"high": 0.5, "avg": 0.34, "low": 0.1, "units": "kg per kg ethanol"}},
    "IL_Pretreatment": {
        "electricity": {"high": 0.06, "avg": 0.04, "low": 0.02, "units": "kg per kg ethanol"},
        "ionicLiquid_amount": {"high": 0.01, "avg": 0.0094, "low": 0.0054, "units": "kg"}, 
        "acid": "h2so4",
        "acid.kg": {"high": 0.0008, "avg": 0.0003, "low": 0.0001, "units": "kg"},
        "water_direct_consumption": {"high": 5, "avg": 3.8, "low": 3, "units": "liter"},
        "water_direct_withdrawal": {"high": 5, "avg": 3.8, "low": 3, "units": "liter"},
        "steam_low": {"high": 0.0006, "avg": 0.0006, "low": 0.0004, "units": "kg"},
        "steam_high": {"high": 0, "avg": 0, "low": 0, "units": "kg"},
        "cooling_water": {"high": 0, "avg": 0, "low": 0, "units": "L"},
        "chilled_water": {"high": 0, "avg": 0, "low": 0, "units": "L"}},
    "Transportation":{},
    "Enzymatic_Hydrolysis_and_Fermentation": {
        "electricity": {"high": 1.2, "avg": 0.9, "low": 0.6, "units": "kg per kg ethanol"},
        "cellulase_amount": {"high": 0.018, "avg": 0.018, "low": 0.018, "units": "kg protein per kg cellulose"}, 
        "dap.kg": {"high": 0.02, "avg": 0.02, "low": 0.02, "units": "g per kg sugar"}, 
        "csl.kg": {"high": 0.16, "avg": 0.16, "low": 0.16, "units": "g per kg sugar"}, 
        "water_direct_consumption": {"high": 6.7, "avg": 6.7, "low": 6.7, "units": "L"},
        "water_direct_withdrawal": {"high": 6.7, "avg": 6.7, "low": 6.7, "units": "liter"},
        "steam_low": {"high": 0.3, "avg": 0.3, "low": 0.3, "units": "kg"},
        "steam_high": {"high": 0, "avg": 0, "low": 0, "units": "kg"},
        "cooling_water": {"high": 122, "avg": 122, "low": 122, "units": "L"},
        "chilled_water": {"high": 0, "avg": 0, "low": 0, "units": "L"},
        "direct_GHG": {"high": 0, "avg": 0, "low": 0, "units": "L"}},
    "Recovery_and_Separation": {
        "electricity": {"high": 0.5, "avg": 0.5, "low": 0.5, "units": "kg per kg ethanol"},
        "water_direct_consumption": {"high": 0, "avg": 0, "low": 0, "units": "L"},
        "water_direct_withdrawal": {"high": 0, "avg": 0, "low": 0, "units": "liter"},
        "steam_low": {"high": 4.8, "avg": 4.8, "low": 4.8, "units": "kg"},
        "steam_high": {"high": 5.6, "avg": 5.6, "low": 5.6, "units": "kg"},
        "cooling_water": {"high": 1700, "avg": 1700, "low": 1700, "units": "L"},
        "chilled_water": {"high": 0, "avg": 0, "low": 0, "units": "L"}},
    "Hydrogeneration_and_Oligomerization": {
        "electricity": {"high": 0.005, "avg": 0.005, "low": 0.005, "units": "kg per kg ethanol"},
        "hydrogen.kg": {"high": 0.015, "avg": 0.015, "low": 0.015, "units": "kg per kg ethanol"}, 
        "chemicals": {"high": 0, "avg": 0, "low": 0, "units": "kg per kg ethanol"},
        "water_direct_consumption": {"high": 0, "avg": 0, "low": 0, "units": "L"},
        "water_direct_withdrawal": {"high": 0, "avg": 0, "low": 0, "units": "liter"},
        "steam_low": {"high": 0, "avg": 0, "low": 0, "units": "kg"},
        "steam_high": {"high": 0.0009, "avg": 0.0009, "low": 0.0009, "units": "kg"},
        "cooling_water": {"high": 20, "avg": 20, "low": 20, "units": "L"},
        "chilled_water": {"high": 3, "avg": 3, "low": 3, "units": "L"}},
    "Wastewater_Treatment": {
        "electricity": {"high": 0.59, "avg": 0.59, "low": 0.59, "units": "kg per kg ethanol"},
        "naoh.kg": {"high": 0.004, "avg": 0.004, "low": 0.004, "units": "kg"},
        "water_direct_consumption": {"high": 12, "avg": 12, "low": 12, "units": "L"},
        "water_direct_withdrawal": {"high": 12, "avg": 12, "low": 12, "units": "liter"},
        "steam_low": {"high": 0.2, "avg": 0.2, "low": 0.2, "units": "kg"},
        "steam_high": {"high": 0, "avg": 0, "low": 0, "units": "kg"},
        "cooling_water": {"high": 0, "avg": 0, "low": 0, "units": "L"},
        "chilled_water": {"high": 0, "avg": 0, "low": 0, "units": "L"}},
    "Lignin_Utilization": {
        "electricity": {"high": 0.5, "avg": 0.5, "low": 0.5, "units": "kg per kg ethanol"},
        "ng_input_stream_MJ": {"high": 0, "avg": 0, "low": 0, "units": "kg"}, 
        "chemicals": {"high": 0, "avg": 0, "low": 0, "units": "kg per kg ethanol"},
        "water_direct_consumption": {"high": 0, "avg": 0, "low": 0, "units": "L"},
        "water_direct_withdrawal": {"high": 0, "avg": 0, "low": 0, "units": "liter"},
        "steam_low": {"high": 12, "avg": 12, "low": 12, "units": "kg"},
        "steam_high": {"high": 0, "avg": 0, "low": 0, "units": "kg"},
        "cooling_water": {"high": 405, "avg": 405, "low": 405, "units": "L"},
        "chilled_water": {"high": 0, "avg": 0, "low": 0, "units": "L"}},
    "Byproducts": {
        "steam_low_credit": {"high": 0, "avg": 0, "low": 0, "units": "kg per kg ethanol"},
        "electricity_credit": {"high": 0, "avg": 0, "low": 0, "units": "kg"}, 
        "water_direct_consumption_credit": {"high": 0, "avg": 0, "low": 0, "units": "kg per kg ethanol"}}}